apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jenkins
spec:
  #  Adjust the cron schedule according to this: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax
  #      ┌────────────────── timezone (optional)
  #      |      ┌───────────── minute (0 - 59)
  #      |      │ ┌───────────── hour (0 - 23)
  #      |      │ │ ┌───────────── day of the month (1 - 31)
  #      |      │ │ │ ┌───────────── month (1 - 12)
  #      |      │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  #      |      │ │ │ │ │                                   7 is also Sunday on some systems)
  #      |      │ │ │ │ │
  #      |      │ │ │ │ │
  # CRON_TZ=UTC * * * * *
  schedule: "CRON_TZ=UTC @midnight" # Run once a day CST Midnight
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 900
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: docker.repo1.uhc.com/busybox
              imagePullPolicy: IfNotPresent
              name: busybox
              resources:
                requests:
                  memory: 256Mi
                  cpu: 125m
                limits:
                  memory: 1024Mi
                  cpu: 250m
              command: [ "/bin/sh","-c" ]
              args:
                - pwd;
                  echo "Success!";
              env:
                - name: JENKINS_HOME
                  value: /var/lib/jenkins
              volumeMounts:
                - mountPath: /var/lib/jenkins
                  name: jenkins
          volumes:
            - name: jenkins
              persistentVolumeClaim:
                claimName: jenkins
