apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    askid: foobar
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  restartPolicy: Never
  containers:
    - image: docker.repo1.uhc.com/riptide/openshift-kubernetes-utilities/jenkins-busybox-alpine:latest
      command: [ "sleep", "6h" ]
      imagePullPolicy: IfNotPresent
      name: busybox
      securityContext:
        capabilities:
          drop: [ "KILL", "MKNOD", "SYS_CHROOT" ]
      env:
        - name: JENKINS_HOME
          value: "/var/lib/jenkins"
      resources:
        requests:
          memory: 256Mi
          cpu: 125m
        limits:
          memory: 1024Mi
          cpu: 250m
      args:
        - touch /tmp/keepalive.txt;
          tail -f /tmp/keepalive.txt;
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - echo readiness
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - echo liveness
      volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins
  volumes:
    - name: jenkins
      persistentVolumeClaim:
        claimName: jenkins


