apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jenkins
spec:
  #  Adjust the cron schedule according to this: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-schedule-syntax
  #      ┌────────────────── timezone (optional)
  #      |      ┌───────────── minute (0 - 59)
  #      |      │ ┌───────────── hour (0 - 23)
  #      |      │ │ ┌───────────── day of the month (1 - 31)
  #      |      │ │ │ ┌───────────── month (1 - 12)
  #      |      │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  #      |      │ │ │ │ │                                   7 is also Sunday on some systems)
  #      |      │ │ │ │ │
  #      |      │ │ │ │ │
  # CRON_TZ=UTC * * * * *
  schedule: "@midnight" # Run once a day CST Midnight
  #  schedule: '*/5 * * * *'
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      template:
        spec:
          containers:
            - image: docker.repo1.uhc.com/busybox
              imagePullPolicy: IfNotPresent
              name: busybox
              resources:
                requests:
                  memory: 1Gi
                  cpu: 100m
                limits:
                  memory: 3Gi
                  cpu: 1000m
              command: [ "/bin/sh","-c" ]
              args:
                - set -o xtrace;
                  echo "pwd = $(pwd)";
                  du -hc -d 1 $JENKINS_HOME/logs;
                  echo "Cleaning up Old .gz logs";
                  find $JENKINS_HOME/logs -name "*.gz" -printf '%p' -delete;
                  echo "Files to Delete:" && ls $JENKINS_HOME/logs/**/* | grep -P "^.+\.log\.\d+$";
                  ls $JENKINS_HOME/logs/**/* | grep -P "^.+\.log\.\d+$" | xargs -d "\n" -I {} rm -v {};
                  echo "Clean up logs/audit/html";
                  mkdir -p $JENKINS_HOME/logs/audit/html && du -ah $JENKINS_HOME/logs/audit/html;
                  ls $JENKINS_HOME/logs/audit/html | grep -P "^audit-\d{4}-\d{2}-\d{2}.html$" | xargs -d "\n" -I {} rm -v {};
                  du -ah $JENKINS_HOME/logs/audit/html;
                  du -hc -d 1 $JENKINS_HOME/logs;
                  du -hc -d 1 $JENKINS_HOME;
                  echo "Success!";
